<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\File;
use Symfony\Component\Finder\Finder;

/**
 * Dev-only utility. Walks ~/projects/income-ops/projects/<slug>/ and
 * extracts a 1-line short_description into
 * database/fixtures/portfolio-bundles/<slug>.md.
 *
 * Why: CI cannot read ~/projects/income-ops/. The DemoProjectsSeeder
 * carries the canonical descriptions inline; this command keeps a
 * mirror snapshot of the source bundles for grep-friendly review and
 * for whatever Phase 5+ tooling wants to lean on the same set without
 * loading the seeder class.
 *
 * Production guard: refuses to run unless App::isLocal() so that a
 * production deploy can't accidentally rewrite committed fixtures
 * from an absent source tree.
 */
class SyncBundleFixturesCommand extends Command
{
    protected $signature = 'codex:sync-bundle-fixtures
        {--source=~/projects/income-ops/projects : root directory of portfolio bundles}
        {--dry-run : print what would be written without touching disk}';

    protected $description = 'Mirrors short_description excerpts from ~/projects/income-ops/projects into the codex fixtures dir. Dev-only.';

    public function handle(): int
    {
        if (! App::isLocal()) {
            $this->error('codex:sync-bundle-fixtures is dev-only — refusing to run outside the local environment.');

            return self::FAILURE;
        }

        $source = $this->expandHome((string) $this->option('source'));
        if (! File::isDirectory($source)) {
            $this->error("Source directory not found: {$source}");

            return self::FAILURE;
        }

        $target = base_path('database/fixtures/portfolio-bundles');
        if (! $this->option('dry-run')) {
            File::ensureDirectoryExists($target);
        }

        $written = 0;
        foreach (Finder::create()->directories()->in($source)->depth(0)->sortByName() as $dir) {
            $slug = $dir->getFilename();
            $description = $this->extractShortDescription($dir->getRealPath());
            if ($description === null) {
                $this->warn(" - {$slug}: no description found, skipping");

                continue;
            }

            $body = "<!-- Source: {$source}/{$slug}/ — generated by codex:sync-bundle-fixtures -->\n\n{$description}\n";
            $path = "{$target}/{$slug}.md";

            if ($this->option('dry-run')) {
                $this->line(" * {$slug}: ".substr($description, 0, 80).(strlen($description) > 80 ? '…' : ''));
            } else {
                File::put($path, $body);
                $written++;
            }
        }

        $this->info($this->option('dry-run')
            ? 'Dry-run complete.'
            : "Wrote {$written} fixture(s) to {$target}.");

        return self::SUCCESS;
    }

    private function extractShortDescription(string $bundleDir): ?string
    {
        // Prefer bundle-portfolio-plan or details-*.md "Short description"
        // fields when present; fall back to the first paragraph of the first
        // .md file alphabetically.
        $candidates = Finder::create()->files()->in($bundleDir)->name('*.md')->sortByName();
        foreach ($candidates as $file) {
            $content = File::get($file->getRealPath());

            // Look for a "Short description:" or "Pitch:" field.
            if (preg_match('/^(?:short[ _-]?description|pitch)\s*[:=]\s*(.+)$/im', $content, $m)) {
                return trim($m[1]);
            }

            // Fall back to first non-empty paragraph after any front-matter / heading.
            $lines = preg_split('/\R/u', $content);
            $body = [];
            $inFrontMatter = false;
            foreach ($lines as $line) {
                $trimmed = trim($line);
                if ($trimmed === '---') {
                    $inFrontMatter = ! $inFrontMatter;

                    continue;
                }
                if ($inFrontMatter || $trimmed === '' || str_starts_with($trimmed, '#')) {
                    if ($body !== []) {
                        break;
                    }

                    continue;
                }
                $body[] = $trimmed;
                if (count($body) >= 3) {
                    break;
                }
            }
            if ($body !== []) {
                return implode(' ', $body);
            }
        }

        return null;
    }

    private function expandHome(string $path): string
    {
        if (str_starts_with($path, '~/')) {
            return ($_SERVER['HOME'] ?? getenv('HOME') ?: '').substr($path, 1);
        }

        return $path;
    }
}
